url: "https://ahnailab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "AhnAILab" # the name of your site, e.g. ACME Corp.
description: "Prof. Ahn's AI LAB"
