menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Hongryul Ahn', title: 'Professor', department: 'Divison of Data Science', institution: 'The University of Suwon', institution_address: 'Hwaseong-si, South Korea', phone: '(031) 229-8762', email: 'hongryulahn@gmail.com', office: 'Building of Global Business, 1012-ho', image: 'assets/img/primary-investigator.jpg', url: 'hongryulahn'}
- {name: 'Seungwon Kim', title: 'Master degree student', department: 'Divison of Data Science', institution: 'The University of Suwon', institution_address: 'Hwaseong-si, South Korea', phone: '(031) 229-8762', email: 'kswon0825@naver.com', office: 'Building of Global Business, 406-ho', image: 'assets/img/graduate-student.jpg', url: 'seungwonkim'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Hongryul Ahn', title: 'Professor', department: 'Divison of Data Science', institution: 'The University of Suwon', institution_address: 'Hwaseong-si, South Korea', phone: '(031) 229-8762', email: 'hongryulahn@gmail.com', office: 'Building of Global Business, 1012-ho', image: 'assets/img/contact.jpg'}
